apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APPLICATION_NAME}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      volumes:
      - name: ${APPLICATION_NAME}
        persistentVolumeClaim:
          claimName: ${APPLICATION_NAME}
      containers:
      - name: ${APPLICATION_NAME}
        image: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # Get environment variables from k8s secret
        envFrom:
        - secretRef:
           name: environment-variables
        # Mounth the image upload directory
        volumeMounts:
        - mountPath: "/usr/share/pv"
          name: ${APPLICATION_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: ClusterIP
  selector:
    app: ${APPLICATION_NAME}
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME} # Name of the ingress, named after the application
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "5g"
    nginx/client_max_body_size: 5g
spec:
  tls:
  - hosts:
    - ${CERTIFICATE_DOMAIN}
    secretName: ${APPLICATION_NAME} # Name of the secret, i.e. the certificates
  rules:
  - host: ${CERTIFICATE_DOMAIN}
    http:
      paths:
      - path: /
        backend:
          serviceName: ${APPLICATION_NAME} # Name of the service, named after the app
          servicePort: 80
